### PR TITLE
Mannheim Contribution #2

### PR DESCRIPTION
**Pull request by crossmanith**
I've followed https://help.github.com/articles/syncing-a-fork and hope that git is happy. github tells me that I'm 4 commits behind NIRALUsers/CCSeg, though.

### CODE REVIEW

**Comment by fbudin69500** [comment]
It seems that you did not synced your repository correctly. When I look at the commits in your repository, you are indeed a few commits behind. Maybe you started to modify the code for your new commits before syncing my commits. If you want to avoid running in that kind of problem, a good way of working is to create a new branch each time you work on a new topic. You can then merge your master with the upstream master, and rebase your branch if necessary.

**Comment by crossmanith** [comment]
In the meantime I started from scratch, i.e. cloned freshly, did one simple change in a new branch. Subsequently I'll provide more useful patches.

**Comment by fbudin69500** [comment]
Should we go ahead and close this pull request?

**Comment by crossmanith** [comment]
Yes  :-)

**Pull request closed without merging**
